### ISSUE TITLE
Story: Get Kuburnetes Working

### ISSUE THREAD

**Issue by Ezequiel-Valencia** [EmuWarfare/Home-Network#25]
### Tasks
- [x] Write initial manifest files for K3s
- [x] Create a production overlay for media
- [x] Install new Proxmox node
   - [x] Backup of VM's on Zima Board
   - [x] Download movie from Jellyfin
   - [x] Shutdown media server
   - [x] Figure out disk storage on ZPC
   - [x] Move VM's on Zima Board to laptop
   - [x] Add ZPC DNS entry, Traefik, and Dashy
   - [x] Install new PC
   - [x] Initialize Proxmox instance on ZPC (ansible, users, etc...)
   - [x] Move media VM to new PC
   - [x] GPU Passthrough for ZPC
   - [x] Properly format different drives and partitions.
- [x] Deploy K3s
   - [x] Get Cert Manager working on minikube
   - [x] Init master node
   - [x] Get Traefik working on my Minikube instance
   - [x] Finish a production overlay
- [x] Deploy K3s and worker nodes in my homelab, ensuring configuration can be done both on my PC and designated control node

### First Notes:
https://github.com/techno-tim/k3s-ansible

https://www.redhat.com/sysadmin/kubespray-deploy-kubernetes

Minikube for testing

Sealed secret for secrets, although once inside cluster these secrets are plain text

https://multipass.run/
