### ISSUE TITLE
Epic: Homelab Cohession 

### ISSUE THREAD

**Issue by Ezequiel-Valencia** [EmuWarfare/Home-Network#9]
### MVP

- Cleaner Ansible scripts
- Internal DNS and dashboard
- Proper certs and domain names for each service available

### Tasks

- [x] #13 
- [x] #14 
- [x] Install Dashy
- [x] #11 
- [x] Update prox to 8.x
- [x] Remove broken 202 node
- [x] #24 
- [x] Single sign on
- [x] Set main DNS for dashy to pihole
- [x] Make more appropriate ansible playbooks
